version: "3.4"
services:
    ingest:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: ingest_service
        hostname: ingestservice
        ports:
            - "3000:3000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 30s
            timeout: 10s
            retries: 5
    scylla:
        image: scylladb/scylla:5.2.0
        restart: always
        container_name: scylladb
        hostname: scylladb
        ports:
            - "9042:9042"
